#!/usr/bin/python3
# SPDX-FileCopyrightText: 2025 Yoshiaki Naruse <zhengyit364@gmail.com>
# SPDX-License-Identifier: BSD-3-Clause

import sys

prog = sys.argv[0]

if len(sys.argv) == 2 and sys.argv[1] in ("-h", "--help"):
    print(f"使い方: cat foods.txt | {prog} <ジャンル1> <ジャンル2> <ジャンル3>", file=sys.stderr)
    sys.exit(0)

if len(sys.argv) != 4:
    print(f"Error: 引数の数が違います。", file=sys.stderr)
    sys.exit(1)

genre1 = sys.argv[1]
genre2 = sys.argv[2]
genre3 = sys.argv[3]

if genre1 not in ("肉", "魚", "麺"):
    print(f"Error: 未対応のジャンル1 '{genre1}'", file=sys.stderr)
    sys.exit(2)

found = False

for line in sys.stdin:
    line = line.strip()
    if not line or line.startswith("#"):
        continue

    try:
        left, name = line.split(":", 1)
        file_g3, file_g2 = left.split(",", 1)
    except ValueError:
        continue

    if file_g2.strip() == genre2 and file_g3.strip() == genre3:
        print(name.strip())
        found = True

if not found:
    print(f"Error: {genre1}, {genre2}, {genre3} なし", file=sys.stderr)
    sys.exit(4)

sys.exit(0)
